-- Generated by scripts/generateSeed.ts — do not edit by hand.
-- Re-run with: `npm run seed:generate`
--
-- Inserts the bundled MVP seed data (src/data/*.json) into the schema
-- defined in supabase/migrations/0001_init.sql. Safe to re-run thanks
-- to ON CONFLICT clauses.

begin;

-- ---------------------------------------------------------------------------
-- programs
-- ---------------------------------------------------------------------------
insert into public.programs (
  id, name, category, county, city, state, description, who_it_helps,
  eligibility_summary, application_method, referral_required, phone,
  website, address, status, status_confidence, source_url, source_type,
  last_verified, notes, priority_score
) values
  ('csv-1y8fvkh', 'Area Agency on Aging and Disabilities of SW WA - Housing Info', 'comprehensive_support', 'Clark', 'Vancouver', 'WA', 'Information and assistance for seniors and people with disabilities.', '{"disability","single_adult"}', 'Seniors or adults with disabilities.', 'phone', false, '360-694-8144', 'https://www.helpingelders.org/', '201 NE 73rd St, Vancouver, WA 98665', 'open', 'high', 'https://www.helpingelders.org/', 'Government', '2026-05-06'::date, 'Serves Clark, Klickitat, Skamania, Cowlitz, and Wahkiakum counties.', 8),
  ('csv-1gz5eqt', 'Clark County Veterans Assistance Center - Outreach', 'comprehensive_support', 'Clark', 'Vancouver', 'WA', 'Outreach to homeless veterans in Clark County.', '{"veteran"}', 'Veteran status.', 'phone', false, '360-693-7030', 'https://ccvac.net/', '1305 Columbia St, Suite 100, Vancouver, WA 98660', 'open', 'high', 'https://ccvac.net/', 'Nonprofit', '2026-05-06'::date, 'Provides gear, food, and connections to housing.', 8),
  ('csv-eq0l00', 'Clark County Veterans Assistance Fund', 'comprehensive_support', 'Clark', 'Vancouver', 'WA', 'Emergency financial assistance for rent, utilities, and other needs.', '{"single_adult","family"}', 'Honorable/General discharge; Clark County resident for 12 months; income <200% poverty.', 'online', false, '360-693-7030', 'https://clark.wa.gov/community-services/veterans-assistance-fund', '1305 Columbia St, Suite 100, Vancouver, WA 98660', 'open', 'high', 'https://clark.wa.gov/community-services/veterans-assistance-fund', 'Government', '2026-05-06'::date, 'Applications accepted M-F 9am-4pm.', 9),
  ('csv-1adub5p', 'Council for the Homeless - Deposit Assistance', 'rental_assistance', 'Clark', 'Vancouver', 'WA', 'Assistance with move-in costs for Clark County residents.', '{"single_adult","family"}', 'Income-based; Clark County resident.', 'phone', false, '360-695-9677', 'https://www.councilforthehomeless.org/', '2501 NE 54th St, Vancouver, WA 98661', 'unknown', 'medium', 'https://www.councilforthehomeless.org/', 'Nonprofit', '2026-05-06'::date, 'Funds are extremely limited.', 7),
  ('clark-council-rent', 'Council for the Homeless Rent Assistance', 'rental_assistance', 'Clark', null, null, null, '{"family","single_adult","senior","disability"}', null, 'phone', false, '(360) 695-9677', 'https://www.councilforthehomeless.org/rent-assistance', null, 'waitlist', 'medium', null, null, '2026-04-14'::date, 'Short-term rental assistance for Clark County residents at risk of homelessness.', 75),
  ('clark-nw-justice', 'Northwest Justice Project Tenant Defense', 'legal_aid', 'Clark', null, null, null, '{"family","single_adult","senior","veteran","disability"}', null, 'phone', false, '(360) 693-6130', 'https://nwjustice.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Free civil legal aid for low-income Washington residents, including eviction defense.', 86),
  ('clark-open-house-ministries', 'Open House Ministries Family Shelter', 'emergency_shelter', 'Clark', null, null, null, '{"family"}', null, 'phone', true, '(360) 737-0300', 'https://ohmkids.org', null, 'waitlist', 'medium', null, null, '2026-04-11'::date, 'Long-term family shelter with education and employment programs.', 70),
  ('clark-share-shelter', 'Share House Men''s Shelter', 'emergency_shelter', 'Clark', null, null, null, '{"single_adult","veteran"}', null, 'walk_in', false, '(360) 695-7658', 'https://sharevancouver.org', null, 'open', 'high', null, null, '2026-04-17'::date, 'Emergency shelter for single men in Vancouver, WA.', 83),
  ('clark-share-transitional', 'Share Transitional Housing', 'transitional_housing', 'Clark', null, null, null, '{"family","single_adult"}', null, 'referral', true, '(360) 448-2121', 'https://sharevancouver.org/housing', null, 'limited', 'medium', null, null, '2026-04-12'::date, '6-24 month transitional housing with case management.', 74),
  ('clark-vha-waitlist', 'Vancouver Housing Authority Section 8', 'long_term_housing_waitlist', 'Clark', null, null, null, '{"single_adult","family","senior","veteran","disability"}', null, 'online', false, '(360) 694-2501', 'https://www.vhausa.com', null, 'closed', 'high', null, null, '2026-04-18'::date, 'Section 8 and public housing waitlist. Currently closed; check site for reopen dates.', 92),
  ('clark-tenant-union', 'Washington Tenants Union Eviction Prevention', 'eviction_prevention', 'Clark', null, null, null, '{"family","single_adult","senior"}', null, 'phone', false, '(206) 723-0500', 'https://tenantsunion.org', null, 'open', 'medium', null, null, '2026-04-10'::date, 'Statewide tenant hotline for rights information and eviction prevention steps.', 72),
  ('csv-1gzk02i', 'YWCA Clark County - SafeChoice Domestic Violence Program', 'emergency_shelter', 'Clark', 'Vancouver', 'WA', 'Emergency shelter and advocacy for survivors of domestic violence.', '{"single_adult","family"}', 'Fleeing domestic violence; prioritizes Clark County survivors.', 'phone', false, '360-695-0501', 'https://www.ywcaclarkcounty.org/', '3609 Main St, Vancouver, WA 98663', 'open', 'high', 'https://www.ywcaclarkcounty.org/', 'Nonprofit', '2026-05-06'::date, 'Includes safety planning and support groups.', 10),
  ('mult-211info', '211info Multnomah', 'comprehensive_support', 'Multnomah', null, null, null, '{"single_adult","family","senior","veteran","disability"}', null, 'phone', false, '211', 'https://www.211info.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Single point of entry for shelter placement, rent assistance referrals, and 24/7 information.', 90),
  ('csv-lqoqkh', 'Bradley Angle - Emergency Shelter', 'emergency_shelter', 'Multnomah', 'Portland', 'OR', 'Confidential emergency shelter for survivors of domestic violence.', '{"family"}', 'Fleeing domestic violence.', 'phone', false, '503-235-5333', 'https://bradleyangle.org/', 'Confidential', 'open', 'high', 'https://bradleyangle.org/', 'Nonprofit', '2026-05-06'::date, 'First DV shelter on the West Coast.', 10),
  ('csv-1nch5zu', 'Catholic Charities - Housing Transitions', 'rental_assistance', 'Multnomah', 'Portland', 'OR', 'Rent assistance and case management for women and families.', '{"family"}', 'Income-based; Multnomah County resident.', 'phone', false, '503-231-4866', 'https://www.catholiccharitiesoregon.org/', '2740 SE Powell Blvd, Portland, OR 97202', 'open', 'high', 'https://www.catholiccharitiesoregon.org/', 'Nonprofit', '2026-05-06'::date, 'Provides specialized support for refugees and immigrants.', 8),
  ('mult-central-city-concern', 'Central City Concern Transitional Housing', 'transitional_housing', 'Multnomah', null, null, null, '{"single_adult","veteran","disability"}', null, 'referral', true, '(503) 294-1681', 'https://centralcityconcern.org', null, 'limited', 'high', null, null, '2026-04-14'::date, 'Recovery-oriented transitional housing with case management and employment services.', 78),
  ('mult-eviction-prevention', 'Community Alliance of Tenants Renters Rights Hotline', 'eviction_prevention', 'Multnomah', null, null, null, '{"family","single_adult","senior"}', null, 'phone', false, '(503) 288-0130', 'https://www.cate-oregon.org', null, 'open', 'high', null, null, '2026-04-17'::date, 'Peer counseling and referrals for tenants at risk of eviction.', 80),
  ('csv-p0gcxk', 'El Programa Hispano Católico - Housing Services', 'rental_assistance', 'Multnomah', 'Gresham', 'OR', 'Culturally specific rent assistance and housing advocacy.', '{"single_adult","family"}', 'Income-based; focus on Latino community.', 'phone', false, '503-669-8350', 'https://www.elprograma.org/', '333 SE 223rd Ave, Suite 100, Gresham, OR 97030', 'open', 'high', 'https://www.elprograma.org/', 'Nonprofit', '2026-05-06'::date, 'Bilingual services available.', 8),
  ('csv-154rdej', 'Human Solutions (Our Just Future) - Deposit Assistance', 'rental_assistance', 'Multnomah', 'Portland', 'OR', 'Move-in assistance for families transitioning to housing.', '{"family"}', 'Families with children; Multnomah County resident.', 'referral', true, '503-548-0200', 'https://ourjustfuture.org/', '12350 SE Powell Blvd, Portland, OR 97236', 'unknown', 'medium', 'https://ourjustfuture.org/', 'Nonprofit', '2026-05-06'::date, 'Part of the Homeless Family System of Care.', 7),
  ('mult-human-solutions-family', 'Human Solutions Family Shelter', 'emergency_shelter', 'Multnomah', null, null, null, '{"family"}', null, 'referral', true, '(503) 548-0200', 'https://humansolutions.org', null, 'waitlist', 'high', null, null, '2026-04-16'::date, 'Family shelter. Call 211 first for placement referral.', 82),
  ('csv-1jr1cb3', 'Impact NW - Deposit Assistance', 'rental_assistance', 'Multnomah', 'Portland', 'OR', 'Help with move-in costs and security deposits.', '{"single_adult","family"}', 'Income-based; Multnomah County resident.', 'referral', true, '503-294-7400', 'https://impactnw.org/', '1005 SE Stark St, Portland, OR 97214', 'unknown', 'medium', 'https://impactnw.org/', 'Nonprofit', '2026-05-06'::date, 'Availability depends on current funding cycles.', 7),
  ('csv-140v1dz', 'Independent Living Resources - Housing Advocacy', 'comprehensive_support', 'Multnomah', 'Portland', 'OR', 'Advocacy and information for people with disabilities seeking housing.', '{"disability"}', 'Living with a disability.', 'phone', false, '503-232-7411', 'https://www.ilr.org/', '1839 NE Couch St, Portland, OR 97232', 'open', 'high', 'https://www.ilr.org/', 'Nonprofit', '2026-05-06'::date, 'Provides peer support and skills training.', 8),
  ('csv-1k8mkjx', 'Janus Youth - Access Center', 'comprehensive_support', 'Multnomah', 'Portland', 'OR', 'Single point-of-entry for youth seeking services through Portland’s Homeless Youth Continuum.', '{"single_adult","family"}', 'Ages 16-24; experiencing homelessness in Multnomah County.', 'phone', false, '503-432-3986', 'https://janusyouth.org/homeless-youth/', '1635 SW Alder Street, Portland, OR 97205', 'open', 'high', 'https://janusyouth.org/homeless-youth/', 'Nonprofit', '2026-05-06'::date, 'Mobile program available 365 days a year.', 10),
  ('csv-grxiq4', 'Janus Youth - The Nest', 'emergency_shelter', 'Multnomah', 'Portland', 'OR', 'Short-term shelter for youth ages 16-24.', '{"single_adult","family"}', 'Ages 16-24; experiencing homelessness.', 'phone', true, '503-432-3986', 'https://janusyouth.org/', 'Confidential', 'open', 'high', 'https://janusyouth.org/', 'Nonprofit', '2026-05-06'::date, 'Focus on stability and long-term housing.', 9),
  ('mult-jrc', 'JOIN Street Outreach', 'emergency_shelter', 'Multnomah', null, null, null, '{"single_adult","disability"}', null, 'walk_in', false, '(503) 232-2031', 'https://joinpdx.org', null, 'open', 'medium', null, null, '2026-04-15'::date, 'Day center plus outreach workers help unsheltered neighbors access services.', 70),
  ('mult-multco-joint-office', 'Multnomah County Joint Office of Homeless Services', 'comprehensive_support', 'Multnomah', null, null, null, '{"single_adult","family","veteran","disability"}', null, 'phone', false, '(503) 988-6295', 'https://www.multco.us/johs', null, 'open', 'high', null, null, '2026-04-18'::date, 'Coordinates shelter, outreach, and housing placement across Multnomah County.', 84),
  ('csv-kqf8tf', 'Native American Youth and Family Center (NAYA) - Housing', 'rental_assistance', 'Multnomah', 'Portland', 'OR', 'Culturally specific rent and housing assistance.', '{"family"}', 'Income-based; focus on Native American community.', 'phone', false, '503-288-8177', 'https://nayapdx.org/', '5135 NE Columbia Blvd, Portland, OR 97218', 'open', 'high', 'https://nayapdx.org/', 'Nonprofit', '2026-05-06'::date, 'Provides wrap-around services and advocacy.', 8),
  ('csv-tjkyvp', 'New Avenues for Youth - Drop-In Center', 'emergency_shelter', 'Multnomah', 'Portland', 'OR', 'Basic needs and connections to housing for youth.', '{"single_adult","family"}', 'Ages 14-24; experiencing or at risk of homelessness.', 'walk_in', false, '503-224-4339', 'https://newavenues.org/', '1635 SW Alder St, Portland, OR 97205', 'open', 'high', 'https://newavenues.org/', 'Nonprofit', '2026-05-06'::date, 'Provides meals, showers, and laundry.', 9),
  ('mult-legal-aid-services', 'Oregon Law Center Eviction Defense', 'legal_aid', 'Multnomah', null, null, null, '{"family","single_adult","senior","veteran","disability"}', null, 'phone', false, '(503) 295-2760', 'https://oregonlawcenter.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Free legal representation for tenants facing eviction. Call ASAP if you have a court date.', 88),
  ('csv-1jnrccn', 'Outside In - Youth Housing', 'emergency_shelter', 'Multnomah', 'Portland', 'OR', 'Transitional and permanent housing for youth.', '{"single_adult","family"}', 'Ages 16-24; experiencing homelessness.', 'phone', false, '503-535-3800', 'https://outsidein.org/', '1132 SW 13th Ave, Portland, OR 97205', 'open', 'high', 'https://outsidein.org/', 'Nonprofit', '2026-05-06'::date, 'Focus on LGBTQ+ and marginalized youth.', 9),
  ('csv-1gnpn07', 'Portland Homeless Family Solutions - Family Shelter', 'emergency_shelter', 'Multnomah', 'Portland', 'OR', 'Emergency shelter and rapid rehousing for families.', '{"family"}', 'Families with at least one minor child.', 'phone', true, '503-915-8306', 'https://www.phfs.org/', '6220 SE 82nd Ave, Portland, OR 97266', 'open', 'high', 'https://www.phfs.org/', 'Nonprofit', '2026-05-06'::date, 'Operates the Family Village shelter.', 9),
  ('csv-196g1m5', 'Raphael House of Portland - Emergency Shelter', 'emergency_shelter', 'Multnomah', 'Portland', 'OR', 'Confidential emergency shelter for survivors of domestic violence.', '{"family"}', 'Fleeing domestic violence.', 'phone', false, '503-222-6222', 'https://raphaelhouse.com/', 'Confidential', 'open', 'high', 'https://raphaelhouse.com/', 'Nonprofit', '2026-05-06'::date, 'Provides housing advocacy and support services.', 10),
  ('csv-1r75qku', 'REACH Community Development - Affordable Housing', 'long_term_housing_waitlist', 'Multnomah', 'Portland', 'OR', 'Develops and manages affordable housing with waitlists.', '{"family"}', 'Income-based (typically <60% AMI).', 'online', false, '503-231-0682', 'https://reachcdc.org/', '4150 SW Moody Ave, Portland, OR 97239', 'open', 'high', 'https://reachcdc.org/', 'Nonprofit', '2026-05-06'::date, 'Waitlists open periodically for specific properties.', 7),
  ('csv-9khq86', 'The Community for Positive Aging - Housing Assistance', 'comprehensive_support', 'Multnomah', 'Portland', 'OR', 'Information and assistance for seniors navigating housing options.', '{"family"}', 'Seniors (typically 60+).', 'phone', false, '503-288-8303', 'https://www.communityfpa.org/', '1820 NE 40th Ave, Portland, OR 97212', 'open', 'high', 'https://www.communityfpa.org/', 'Nonprofit', '2026-05-06'::date, 'Formerly Hollywood Senior Center.', 8),
  ('csv-tkhh8', 'Transition Projects - SSVF (Supportive Services for Veteran Families)', 'comprehensive_support', 'Multnomah', 'Portland', 'OR', 'Rapid rehousing and homelessness prevention for veterans and their families.', '{"family","veteran"}', 'Served in U.S. Military; experiencing or at risk of homelessness; low-income.', 'online', false, '855-425-5544', 'https://www.tprojects.org/veterans-services', '665 NW Hoyt St, Portland, OR 97209', 'open', 'high', 'https://www.tprojects.org/veterans-services', 'Nonprofit', '2026-05-06'::date, 'CARF accredited program.', 10),
  ('mult-transition-projects', 'Transition Projects Shelter Intake', 'emergency_shelter', 'Multnomah', null, null, null, '{"single_adult","veteran"}', null, 'walk_in', false, '(503) 280-4700', 'https://www.tprojects.org', null, 'limited', 'high', null, null, '2026-04-17'::date, 'Walk-in shelter for single adults. Limited beds; arrive early.', 85),
  ('csv-o9nfbf', 'Urban League of Portland - Housing Department', 'rental_assistance', 'Multnomah', 'Portland', 'OR', 'Culturally specific rent assistance and eviction prevention.', '{"single_adult","family"}', 'Income-based; Multnomah County resident.', 'phone', false, '503-280-2600', 'https://ulpdx.org/', '10 N Russell St, Portland, OR 97227', 'open', 'high', 'https://ulpdx.org/', 'Nonprofit', '2026-05-06'::date, 'Focus on housing stability and advocacy.', 8),
  ('csv-12oi571', 'VA Portland Health Care - Homeless Veteran Care', 'comprehensive_support', 'Multnomah', 'Portland', 'OR', 'Comprehensive services for homeless veterans including HUD-VASH vouchers.', '{"veteran"}', 'Veteran status; homeless or at risk.', 'phone', false, '877-424-3838', 'https://www.va.gov/portland-health-care/health-services/homeless-veteran-care/', '308 SW 1st Ave, Portland, OR 97204 (CRRC)', 'open', 'high', 'https://www.va.gov/portland-health-care/health-services/homeless-veteran-care/', 'Government', '2026-05-06'::date, 'CRRC is the Community Resource and Referral Center.', 10)
on conflict (id) do update set
  name                = excluded.name,
  category            = excluded.category,
  county              = excluded.county,
  city                = excluded.city,
  state               = excluded.state,
  description         = excluded.description,
  who_it_helps        = excluded.who_it_helps,
  eligibility_summary = excluded.eligibility_summary,
  application_method  = excluded.application_method,
  referral_required   = excluded.referral_required,
  phone               = excluded.phone,
  website             = excluded.website,
  address             = excluded.address,
  status              = excluded.status,
  status_confidence   = excluded.status_confidence,
  source_url          = excluded.source_url,
  source_type         = excluded.source_type,
  last_verified       = excluded.last_verified,
  notes               = excluded.notes,
  priority_score      = excluded.priority_score;

-- ---------------------------------------------------------------------------
-- decision_rules
-- ---------------------------------------------------------------------------
insert into public.decision_rules (
  intake_state, goal, primary_action, priority_categories,
  secondary_categories, recommended_documents, caution_notes
) values
  ('homeless', 'shelter', 'Call 211 (Multnomah) or the Council for the Homeless Housing Hotline at (360) 695-9677 (Clark) for same-day shelter placement.', '{"emergency_shelter","comprehensive_support"}', '{"transitional_housing","long_term_housing_waitlist"}', '{"Photo ID (if available)","Social Security card (if available)","Medical/medication list","Contact info for any case worker"}', '{"Shelter capacity changes daily. If the first option is full, call back or try another on the list.","Bring any ID you have, but lack of ID will not disqualify you from emergency shelter."}'),
  ('eviction_notice', 'stay_housed', 'Contact a legal aid eviction defense line TODAY. In Multnomah call Oregon Law Center at (503) 295-2760; in Clark call Northwest Justice Project at (360) 693-6130.', '{"legal_aid","eviction_prevention","rental_assistance"}', '{"comprehensive_support","emergency_shelter"}', '{"The eviction notice (all pages and envelope)","Your lease or rental agreement","Proof of rent payments (receipts, bank statements)","Photo ID","Proof of income (last 30 days)"}', '{"Do NOT ignore the notice. Deadlines are short (often 72 hours to 10 days).","Do not move out voluntarily before talking to legal aid — you may have more rights than you think.","Keep every document and envelope you receive from your landlord."}'),
  ('at_risk', 'stay_housed', 'Apply for short-term rent assistance before you fall further behind. Start with 211 (Multnomah) or Council for the Homeless (Clark).', '{"rental_assistance","eviction_prevention"}', '{"legal_aid","comprehensive_support"}', '{"Current lease","Proof of income (last 30 days)","Past-due rent notice or ledger from landlord","Photo ID","Bills showing hardship (medical, utilities, etc.)"}', '{"Most rent assistance programs require you to apply BEFORE an eviction is filed.","Talk to your landlord in writing about a payment plan — put everything in email or text."}'),
  ('at_risk', 'long_term_housing', 'Get on every open housing authority waitlist you qualify for. Use the waitlist tracker to see which county lists are open today.', '{"long_term_housing_waitlist","transitional_housing"}', '{"rental_assistance","comprehensive_support"}', '{"Photo ID for every adult in the household","Social Security cards or numbers for all household members","Birth certificates for children","Proof of income for all adults","Current address and 2 years of address history"}', '{"Waitlists can take months or years. Apply to multiple simultaneously.","Update your contact info with each authority regularly — missed letters are a common reason people get dropped.","Some waitlists are only open for short windows — check status frequently."}')
on conflict (intake_state, goal) do update set
  primary_action        = excluded.primary_action,
  priority_categories   = excluded.priority_categories,
  secondary_categories  = excluded.secondary_categories,
  recommended_documents = excluded.recommended_documents,
  caution_notes         = excluded.caution_notes;

-- ---------------------------------------------------------------------------
-- waitlists
-- ---------------------------------------------------------------------------
insert into public.waitlists (
  id, housing_authority, program_name, county, status, application_link,
  source_url, last_checked, notes
) values
  ('vha', 'Vancouver Housing Authority (Clark)', null, 'Clark', 'closed', 'https://www.vhausa.com/apply-for-housing', null, '2026-04-18'::date, 'General waitlist closed. Monitor site for reopen announcements.'),
  ('clackamas-housing', 'Clackamas County Housing Authority', null, 'Clackamas', 'unknown', 'https://www.clackamas.us/housingauthority', null, '2026-03-24'::date, 'Status last confirmed in March; call (503) 655-8267 to verify.'),
  ('washington-housing', 'Washington County Dept. of Housing Services', null, 'Washington', 'closed', 'https://www.washingtoncountyor.gov/housing', null, '2026-04-18'::date, 'Waitlist closed. Project-based waitlists open periodically — check site.'),
  ('council-for-homeless', 'Council for the Homeless Coordinated Entry', null, 'Clark', 'open', 'https://www.councilforthehomeless.org', null, '2026-04-18'::date, 'Single front door for shelter and housing in Clark County.')
on conflict (id) do update set
  housing_authority = excluded.housing_authority,
  program_name      = excluded.program_name,
  county            = excluded.county,
  status            = excluded.status,
  application_link  = excluded.application_link,
  source_url        = excluded.source_url,
  last_checked      = excluded.last_checked,
  notes             = excluded.notes;

commit;
