-- Generated by scripts/generateSeed.ts — do not edit by hand.
-- Re-run with: `npm run seed:generate`
--
-- Inserts the bundled MVP seed data (src/data/*.json) into the schema
-- defined in supabase/migrations/0001_init.sql. Safe to re-run thanks
-- to ON CONFLICT clauses.

begin;

-- ---------------------------------------------------------------------------
-- programs
-- ---------------------------------------------------------------------------
insert into public.programs (
  id, name, category, county, city, state, description, who_it_helps,
  eligibility_summary, application_method, referral_required, phone,
  website, address, status, status_confidence, source_url, source_type,
  last_verified, notes, priority_score
) values
  ('mult-211info', '211info Multnomah', 'comprehensive_support', 'Multnomah', null, null, null, '{"single_adult","family","senior","veteran","disability"}', null, 'phone', false, '211', 'https://www.211info.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Single point of entry for shelter placement, rent assistance referrals, and 24/7 information.', 90),
  ('mult-transition-projects', 'Transition Projects Shelter Intake', 'emergency_shelter', 'Multnomah', null, null, null, '{"single_adult","veteran"}', null, 'walk_in', false, '(503) 280-4700', 'https://www.tprojects.org', null, 'limited', 'high', null, null, '2026-04-17'::date, 'Walk-in shelter for single adults. Limited beds; arrive early.', 85),
  ('mult-human-solutions-family', 'Human Solutions Family Shelter', 'emergency_shelter', 'Multnomah', null, null, null, '{"family"}', null, 'referral', true, '(503) 548-0200', 'https://humansolutions.org', null, 'waitlist', 'high', null, null, '2026-04-16'::date, 'Family shelter. Call 211 first for placement referral.', 82),
  ('mult-jrc', 'JOIN Street Outreach', 'emergency_shelter', 'Multnomah', null, null, null, '{"single_adult","disability"}', null, 'walk_in', false, '(503) 232-2031', 'https://joinpdx.org', null, 'open', 'medium', null, null, '2026-04-15'::date, 'Day center plus outreach workers help unsheltered neighbors access services.', 70),
  ('mult-home-forward-waitlist', 'Home Forward Section 8 / Public Housing', 'long_term_housing_waitlist', 'Multnomah', null, null, null, '{"single_adult","family","senior","veteran","disability"}', null, 'online', false, '(503) 802-8333', 'https://homeforward.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Multnomah County''s primary public housing authority. Waitlist currently open for select programs.', 95),
  ('mult-central-city-concern', 'Central City Concern Transitional Housing', 'transitional_housing', 'Multnomah', null, null, null, '{"single_adult","veteran","disability"}', null, 'referral', true, '(503) 294-1681', 'https://centralcityconcern.org', null, 'limited', 'high', null, null, '2026-04-14'::date, 'Recovery-oriented transitional housing with case management and employment services.', 78),
  ('mult-impact-nw-rent', 'Impact NW Rent Assistance', 'rental_assistance', 'Multnomah', null, null, null, '{"family","single_adult","senior"}', null, 'online', false, '(503) 988-6000', 'https://impactnw.org', null, 'waitlist', 'medium', null, null, '2026-04-12'::date, 'Short-term rent and utility assistance for low-income households in Multnomah County.', 72),
  ('mult-legal-aid-services', 'Oregon Law Center Eviction Defense', 'legal_aid', 'Multnomah', null, null, null, '{"family","single_adult","senior","veteran","disability"}', null, 'phone', false, '(503) 295-2760', 'https://oregonlawcenter.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Free legal representation for tenants facing eviction. Call ASAP if you have a court date.', 88),
  ('mult-eviction-prevention', 'Community Alliance of Tenants Renters Rights Hotline', 'eviction_prevention', 'Multnomah', null, null, null, '{"family","single_adult","senior"}', null, 'phone', false, '(503) 288-0130', 'https://www.cate-oregon.org', null, 'open', 'high', null, null, '2026-04-17'::date, 'Peer counseling and referrals for tenants at risk of eviction.', 80),
  ('mult-multco-joint-office', 'Multnomah County Joint Office of Homeless Services', 'comprehensive_support', 'Multnomah', null, null, null, '{"single_adult","family","veteran","disability"}', null, 'phone', false, '(503) 988-6295', 'https://www.multco.us/johs', null, 'open', 'high', null, null, '2026-04-18'::date, 'Coordinates shelter, outreach, and housing placement across Multnomah County.', 84),
  ('clark-council-aging', 'Council for the Homeless Housing Hotline', 'comprehensive_support', 'Clark', null, null, null, '{"single_adult","family","senior","veteran","disability"}', null, 'phone', false, '(360) 695-9677', 'https://www.councilforthehomeless.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Clark County''s coordinated entry point. First call for shelter or rent help.', 90),
  ('clark-share-shelter', 'Share House Men''s Shelter', 'emergency_shelter', 'Clark', null, null, null, '{"single_adult","veteran"}', null, 'walk_in', false, '(360) 695-7658', 'https://sharevancouver.org', null, 'open', 'high', null, null, '2026-04-17'::date, 'Emergency shelter for single men in Vancouver, WA.', 83),
  ('clark-ywca-family', 'YWCA Clark County SafeChoice Shelter', 'emergency_shelter', 'Clark', null, null, null, '{"family","single_adult"}', null, 'phone', false, '(360) 695-0501', 'https://www.ywcaclarkcounty.org', null, 'limited', 'medium', null, null, '2026-04-15'::date, 'Shelter and services for survivors of domestic violence and families in crisis.', 78),
  ('clark-vha-waitlist', 'Vancouver Housing Authority Section 8', 'long_term_housing_waitlist', 'Clark', null, null, null, '{"single_adult","family","senior","veteran","disability"}', null, 'online', false, '(360) 694-2501', 'https://www.vhausa.com', null, 'closed', 'high', null, null, '2026-04-18'::date, 'Section 8 and public housing waitlist. Currently closed; check site for reopen dates.', 92),
  ('clark-share-transitional', 'Share Transitional Housing', 'transitional_housing', 'Clark', null, null, null, '{"family","single_adult"}', null, 'referral', true, '(360) 448-2121', 'https://sharevancouver.org/housing', null, 'limited', 'medium', null, null, '2026-04-12'::date, '6-24 month transitional housing with case management.', 74),
  ('clark-council-rent', 'Council for the Homeless Rent Assistance', 'rental_assistance', 'Clark', null, null, null, '{"family","single_adult","senior","disability"}', null, 'phone', false, '(360) 695-9677', 'https://www.councilforthehomeless.org/rent-assistance', null, 'waitlist', 'medium', null, null, '2026-04-14'::date, 'Short-term rental assistance for Clark County residents at risk of homelessness.', 75),
  ('clark-nw-justice', 'Northwest Justice Project Tenant Defense', 'legal_aid', 'Clark', null, null, null, '{"family","single_adult","senior","veteran","disability"}', null, 'phone', false, '(360) 693-6130', 'https://nwjustice.org', null, 'open', 'high', null, null, '2026-04-18'::date, 'Free civil legal aid for low-income Washington residents, including eviction defense.', 86),
  ('clark-tenant-union', 'Washington Tenants Union Eviction Prevention', 'eviction_prevention', 'Clark', null, null, null, '{"family","single_adult","senior"}', null, 'phone', false, '(206) 723-0500', 'https://tenantsunion.org', null, 'open', 'medium', null, null, '2026-04-10'::date, 'Statewide tenant hotline for rights information and eviction prevention steps.', 72),
  ('clark-open-house-ministries', 'Open House Ministries Family Shelter', 'emergency_shelter', 'Clark', null, null, null, '{"family"}', null, 'phone', true, '(360) 737-0300', 'https://ohmkids.org', null, 'waitlist', 'medium', null, null, '2026-04-11'::date, 'Long-term family shelter with education and employment programs.', 70)
on conflict (id) do update set
  name                = excluded.name,
  category            = excluded.category,
  county              = excluded.county,
  city                = excluded.city,
  state               = excluded.state,
  description         = excluded.description,
  who_it_helps        = excluded.who_it_helps,
  eligibility_summary = excluded.eligibility_summary,
  application_method  = excluded.application_method,
  referral_required   = excluded.referral_required,
  phone               = excluded.phone,
  website             = excluded.website,
  address             = excluded.address,
  status              = excluded.status,
  status_confidence   = excluded.status_confidence,
  source_url          = excluded.source_url,
  source_type         = excluded.source_type,
  last_verified       = excluded.last_verified,
  notes               = excluded.notes,
  priority_score      = excluded.priority_score;

-- ---------------------------------------------------------------------------
-- decision_rules
-- ---------------------------------------------------------------------------
insert into public.decision_rules (
  intake_state, goal, primary_action, priority_categories,
  secondary_categories, recommended_documents, caution_notes
) values
  ('homeless', 'shelter', 'Call 211 (Multnomah) or the Council for the Homeless Housing Hotline at (360) 695-9677 (Clark) for same-day shelter placement.', '{"emergency_shelter","comprehensive_support"}', '{"transitional_housing","long_term_housing_waitlist"}', '{"Photo ID (if available)","Social Security card (if available)","Medical/medication list","Contact info for any case worker"}', '{"Shelter capacity changes daily. If the first option is full, call back or try another on the list.","Bring any ID you have, but lack of ID will not disqualify you from emergency shelter."}'),
  ('eviction_notice', 'stay_housed', 'Contact a legal aid eviction defense line TODAY. In Multnomah call Oregon Law Center at (503) 295-2760; in Clark call Northwest Justice Project at (360) 693-6130.', '{"legal_aid","eviction_prevention","rental_assistance"}', '{"comprehensive_support","emergency_shelter"}', '{"The eviction notice (all pages and envelope)","Your lease or rental agreement","Proof of rent payments (receipts, bank statements)","Photo ID","Proof of income (last 30 days)"}', '{"Do NOT ignore the notice. Deadlines are short (often 72 hours to 10 days).","Do not move out voluntarily before talking to legal aid — you may have more rights than you think.","Keep every document and envelope you receive from your landlord."}'),
  ('at_risk', 'stay_housed', 'Apply for short-term rent assistance before you fall further behind. Start with 211 (Multnomah) or Council for the Homeless (Clark).', '{"rental_assistance","eviction_prevention"}', '{"legal_aid","comprehensive_support"}', '{"Current lease","Proof of income (last 30 days)","Past-due rent notice or ledger from landlord","Photo ID","Bills showing hardship (medical, utilities, etc.)"}', '{"Most rent assistance programs require you to apply BEFORE an eviction is filed.","Talk to your landlord in writing about a payment plan — put everything in email or text."}'),
  ('at_risk', 'long_term_housing', 'Get on every open housing authority waitlist you qualify for. Check Home Forward (Multnomah) and Vancouver Housing Authority (Clark) today.', '{"long_term_housing_waitlist","transitional_housing"}', '{"rental_assistance","comprehensive_support"}', '{"Photo ID for every adult in the household","Social Security cards or numbers for all household members","Birth certificates for children","Proof of income for all adults","Current address and 2 years of address history"}', '{"Waitlists can take months or years. Apply to multiple simultaneously.","Update your contact info with each authority regularly — missed letters are a common reason people get dropped.","Some waitlists are only open for short windows — check status frequently."}')
on conflict (intake_state, goal) do update set
  primary_action        = excluded.primary_action,
  priority_categories   = excluded.priority_categories,
  secondary_categories  = excluded.secondary_categories,
  recommended_documents = excluded.recommended_documents,
  caution_notes         = excluded.caution_notes;

-- ---------------------------------------------------------------------------
-- waitlists
-- ---------------------------------------------------------------------------
insert into public.waitlists (
  id, housing_authority, program_name, county, status, application_link,
  source_url, last_checked, notes
) values
  ('home-forward', 'Home Forward (Multnomah)', null, 'Multnomah', 'open', 'https://homeforward.org/find-a-home', null, '2026-04-18'::date, 'Section 8 Housing Choice Voucher waitlist currently accepting applications for select properties.'),
  ('vha', 'Vancouver Housing Authority (Clark)', null, 'Clark', 'closed', 'https://www.vhausa.com/apply-for-housing', null, '2026-04-18'::date, 'General waitlist closed. Monitor site for reopen announcements.'),
  ('clackamas-housing', 'Clackamas County Housing Authority', null, 'Clackamas', 'unknown', 'https://www.clackamas.us/housingauthority', null, '2026-03-24'::date, 'Status last confirmed in March; call (503) 655-8267 to verify.'),
  ('washington-housing', 'Washington County Dept. of Housing Services', null, 'Washington', 'closed', 'https://www.washingtoncountyor.gov/housing', null, '2026-04-18'::date, 'Waitlist closed. Project-based waitlists open periodically — check site.'),
  ('hacsa-multnomah', 'Home Forward Short Term Rent Assistance', null, 'Multnomah', 'open', 'https://homeforward.org/rent-assistance', null, '2026-04-17'::date, 'Apply through community partner agencies. Funds limited.'),
  ('council-for-homeless', 'Council for the Homeless Coordinated Entry', null, 'Clark', 'open', 'https://www.councilforthehomeless.org', null, '2026-04-18'::date, 'Single front door for shelter and housing in Clark County.')
on conflict (id) do update set
  housing_authority = excluded.housing_authority,
  program_name      = excluded.program_name,
  county            = excluded.county,
  status            = excluded.status,
  application_link  = excluded.application_link,
  source_url        = excluded.source_url,
  last_checked      = excluded.last_checked,
  notes             = excluded.notes;

commit;
