/**
 * Generate `supabase/seed.sql` from the bundled JSON in `src/data`.
 *
 * Run with: `npm run seed:generate`
 *
 * Output is committed to source so a Supabase project can be brought up
 * with `supabase db reset` (or `psql -f supabase/seed.sql`) without
 * needing Node tooling at deploy time.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { ProgramRow, WaitlistRow } from '../src/services/data/dbTypes.ts';
import { programToRow } from '../src/services/data/mappers.ts';
import type { DecisionRule, Program, WaitlistEntry } from '../src/types/index.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');

function read<T>(relativePath: string): T {
  const absolute = join(repoRoot, relativePath);
  return JSON.parse(readFileSync(absolute, 'utf8')) as T;
}

// Seed from the merged catalog so Supabase mirrors what the app serves.
// Falls back to the legacy `programs.json` if the catalog has not been
// generated yet (fresh clone). Run `npm run catalog:build` first if you
// want CSV rows in the seed output.
let programs: Program[];
try {
  programs = read<Program[]>('src/data/catalog.json');
} catch {
  programs = read<Program[]>('src/data/programs.json');
}
const rules = read<DecisionRule[]>('src/data/decisionRules.json');
const waitlists = read<WaitlistEntry[]>('src/data/waitlists.json');

function quote(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function bool(value: boolean): string {
  return value ? 'true' : 'false';
}

function intLiteral(value: number): string {
  return String(value);
}

function dateLiteral(value: string | null | undefined): string {
  if (!value) return 'null';
  return `'${value.replace(/'/g, "''")}'::date`;
}

function textArray(values: readonly string[]): string {
  if (values.length === 0) return "'{}'";
  const escaped = values.map((v) => `"${v.replace(/"/g, '\\"')}"`).join(',');
  return `'{${escaped}}'`;
}

function programInsert(p: Program): string {
  const row: ProgramRow = programToRow(p);
  const cols = [
    quote(row.id),
    quote(row.name),
    quote(row.category),
    quote(row.county),
    quote(row.city),
    quote(row.state),
    quote(row.description),
    textArray(row.who_it_helps),
    quote(row.eligibility_summary),
    quote(row.application_method),
    bool(row.referral_required),
    quote(row.phone),
    quote(row.website),
    quote(row.address),
    quote(row.status),
    quote(row.status_confidence),
    quote(row.source_url),
    quote(row.source_type),
    dateLiteral(row.last_verified),
    quote(row.notes),
    intLiteral(row.priority_score),
  ];
  return `(${cols.join(', ')})`;
}

function ruleInsert(r: DecisionRule): string {
  const cols = [
    quote(r.intake_state),
    quote(r.goal),
    quote(r.primary_action),
    textArray(r.priority_categories),
    textArray(r.secondary_categories),
    textArray(r.recommended_documents),
    textArray(r.caution_notes),
  ];
  return `(${cols.join(', ')})`;
}

function waitlistInsert(w: WaitlistEntry): string {
  const housingAuthority = w.housing_authority ?? w.agency;
  const programName = w.program_name ?? null;
  const applicationLink = w.application_link ?? w.website ?? null;
  const cols = [
    quote(w.id),
    quote(housingAuthority),
    quote(programName),
    quote(w.county),
    quote(w.status),
    quote(applicationLink),
    quote(w.source_url ?? null),
    dateLiteral(w.last_checked),
    quote(w.notes ?? null),
  ];
  return `(${cols.join(', ')})`;
}

const programsValues = programs.map(programInsert).join(',\n  ');
const rulesValues = rules.map(ruleInsert).join(',\n  ');
const waitlistsValues = waitlists.map(waitlistInsert).join(',\n  ');

const sql = `-- Generated by scripts/generateSeed.ts — do not edit by hand.
-- Re-run with: \`npm run seed:generate\`
--
-- Inserts the bundled MVP seed data (src/data/*.json) into the schema
-- defined in supabase/migrations/0001_init.sql. Safe to re-run thanks
-- to ON CONFLICT clauses.

begin;

-- ---------------------------------------------------------------------------
-- programs
-- ---------------------------------------------------------------------------
insert into public.programs (
  id, name, category, county, city, state, description, who_it_helps,
  eligibility_summary, application_method, referral_required, phone,
  website, address, status, status_confidence, source_url, source_type,
  last_verified, notes, priority_score
) values
  ${programsValues}
on conflict (id) do update set
  name                = excluded.name,
  category            = excluded.category,
  county              = excluded.county,
  city                = excluded.city,
  state               = excluded.state,
  description         = excluded.description,
  who_it_helps        = excluded.who_it_helps,
  eligibility_summary = excluded.eligibility_summary,
  application_method  = excluded.application_method,
  referral_required   = excluded.referral_required,
  phone               = excluded.phone,
  website             = excluded.website,
  address             = excluded.address,
  status              = excluded.status,
  status_confidence   = excluded.status_confidence,
  source_url          = excluded.source_url,
  source_type         = excluded.source_type,
  last_verified       = excluded.last_verified,
  notes               = excluded.notes,
  priority_score      = excluded.priority_score;

-- ---------------------------------------------------------------------------
-- decision_rules
-- ---------------------------------------------------------------------------
insert into public.decision_rules (
  intake_state, goal, primary_action, priority_categories,
  secondary_categories, recommended_documents, caution_notes
) values
  ${rulesValues}
on conflict (intake_state, goal) do update set
  primary_action        = excluded.primary_action,
  priority_categories   = excluded.priority_categories,
  secondary_categories  = excluded.secondary_categories,
  recommended_documents = excluded.recommended_documents,
  caution_notes         = excluded.caution_notes;

-- ---------------------------------------------------------------------------
-- waitlists
-- ---------------------------------------------------------------------------
insert into public.waitlists (
  id, housing_authority, program_name, county, status, application_link,
  source_url, last_checked, notes
) values
  ${waitlistsValues}
on conflict (id) do update set
  housing_authority = excluded.housing_authority,
  program_name      = excluded.program_name,
  county            = excluded.county,
  status            = excluded.status,
  application_link  = excluded.application_link,
  source_url        = excluded.source_url,
  last_checked      = excluded.last_checked,
  notes             = excluded.notes;

commit;
`;

const outPath = join(repoRoot, 'supabase', 'seed.sql');
writeFileSync(outPath, sql, 'utf8');
console.log(`Wrote ${outPath} (${programs.length} programs, ${rules.length} rules, ${waitlists.length} waitlists).`);
